print handler messages to stderr, not stdout (thx mmarek)

diff --git a/handlers/bin/command_not_found_bash b/handlers/bin/command_not_found_bash
--- a/handlers/bin/command_not_found_bash
+++ b/handlers/bin/command_not_found_bash
@@ -8,21 +8,21 @@ command_not_found_handle() {
 
     # do not run when inside Midnight Commander or within a Pipe
     if test -n "$MC_SID" -o ! -t 1 ; then
-        echo $"$1: command not found"
+        echo $"$1: command not found" >&2
         return 127
     fi
 
     # do not run when within a subshell
     read pid cmd state ppid pgrp session tty_nr tpgid rest  < /proc/self/stat
     if test $$ -eq $tpgid ; then
-        echo "$1: command not found"
+        echo "$1: command not found" >&2
         return 127
     fi
 
     # test for /usr/sbin and /sbin
     if test -x "/usr/sbin/$1" -o -x "/sbin/$1" ; then
         if test -x "/usr/sbin/$1" ; then prefix='/usr' ; else prefix='' ; fi
-        echo $"Absolute path to '$1' is '$prefix/sbin/$1', so running it may require superuser privileges (eg. root)."
+        echo $"Absolute path to '$1' is '$prefix/sbin/$1', so running it may require superuser privileges (eg. root)." >&2
         return 127
     fi
 
@@ -32,7 +32,7 @@ command_not_found_handle() {
     else
         # print only info about command-not-found
         echo -e $"If '$1' is not a typo you can use command-not-found to lookup the package that contains it, like this:
-    cnf $1"
+    cnf $1" >&2
     fi
 
     return 127
